Build pipeline for main branch.
microsoftgraph/msgraph-typescript-typings pull request #350
Opened 2022-12-01 23:49 UTC by nikithauc

2022-12-01 23:56 UTC, zengin approved these changes

2022-12-02 00:02 UTC, MIchaelMainer requested changes

2022-12-02 00:02 UTC, MIchaelMainer commented on .azure-pipelines/common-templates/security-post-checks.yml
> +      RoslynAnalyzers: true
```suggestion
      RoslynAnalyzers: false
```

2022-12-02 00:02 UTC, MIchaelMainer commented on .azure-pipelines/common-templates/security-post-checks.yml
> +      TSLint: false
```suggestion
      TSLint: true
```

2022-12-02 00:02 UTC, MIchaelMainer commented on .azure-pipelines/common-templates/security-post-checks.yml
> +      CodesignValidation: true
```suggestion
      CodesignValidation: false
```

2022-12-02 00:02 UTC, MIchaelMainer commented on .azure-pipelines/common-templates/security-post-checks.yml
> +      CodesignValidation: true
```suggestion
      CodesignValidation: false
```

2022-12-02 00:02 UTC, MIchaelMainer commented on .azure-pipelines/common-templates/security-post-checks.yml
> +      RoslynAnalyzers: true
```suggestion
      RoslynAnalyzers: false
```

2022-12-28 20:12 UTC, zengin approved these changes

2023-02-02 20:17 UTC, nikithauc commented on .azure-pipelines/ci-build-production.yml
> +    Contents: |
Done 
Please check
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - microsoft-graph.d.ts

2023-02-02 20:22 UTC, MIchaelMainer approved these changes

2023-02-02 20:27 UTC, merged